app:
  page_title: "Wardrobe Manager"
  page_icon: "ğŸ‘•"
home:
  title: "ğŸ”ğŸ‘• Wardrobe Manager ğŸ‘šğŸ“ˆ"
  onboarding:
    - "## Welcome to the Wardrobe Manager! ğŸ‘‹"
    - "### This app will help you keep track of the items in your wardrobe. ğŸ“ˆğŸ¤©"
    - "- 1ï¸âƒ£ To get started, take a picture of the items in your wardrobe. ğŸ“¸"
    - "- 2ï¸âƒ£ Then, select the category of the item. ğŸ‘šğŸ‘•ğŸ‘”ğŸ‘–ğŸ©³"
    - "- 3ï¸âƒ£ Finally, select the date you wore the item. ğŸ“…"
    - "### âœ¨ Once you've done that, you can submit the item to your wardrobe tracker. ğŸ“¤â˜ï¸"
  camera_instruction: "Take a picture of the items in your wardrobe ğŸ“¸"
  select:
    instruction: "Select the category of the item: ğŸ‘šğŸ‘•ğŸ‘”ğŸ‘–ğŸ©³"
    options:
      - "T-Shirt ğŸ‘•"
      - "Blouse ğŸ‘š"
      - "Shirt ğŸ‘”"
      - "Pants ğŸ‘–"
      - "Shorts ğŸ©³"
  date_instruction: "Select the date you wore the item: ğŸ“…"
  submit_instruction: "Submit the item to your wardrobe tracker: ğŸ“¤â˜ï¸"
tracker:
  title: "ğŸ“ˆ Wardrobe Tracker ğŸ“ˆ"
